version = "1.1.11"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
client = "{icon}{delim}"
client_active = "{icon}"
workspace = "<b>{id}:</b>{delim}{clients}"
workspace_empty = "<b>{id}:</b>{delim}{clients}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon}]{delim}"

[title_in_class."(firefox|chrom.*|Brave)"]
"(?i)youtube" = "ꟳ"
"(?i)twitch" = "ꟳ"

[class]
DEFAULT = ""
"(?i)firefox" = "<span color='orange'> </span>"
"Brave" = ""
"(?i)kitty" = ""
"(?i)alacritty" = ""
bleachbit = ""
burp-startburp = ""
calibre-gui = ""
"chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default" = ""
chromium = ""
"Gimp-2.10" = ""
code-oss = ""
cssh = ""
darktable = ""
discord = ""
dmenu-clipboard = ""
dmenu-pass = ""
duolingo = ""
element = ""
fontforge = ""
gcr-prompter = ""
gsimplecalc = ""
"jetbrains-studio" = ""
"kak" = ""
kicad = ""
"(?i)waydroid.*" = "droid"
obsidian = ""
"dmenu-emoji" = ""
"dmenu-browser" = ""
"dmenu-pass generator" = ""
"qalculate-gtk" = ""
krita = ""
libreoffice-calc = ""
libreoffice-impress = ""
libreoffice-startcenter = ""
libreoffice-writer = ""
molotov = ""
mpv = ""
neomutt = ""
nm-connection-editor = ""
org-ksnip-ksnip = ""
org-pwmt-zathura = ""
org-qutebrowser-qutebrowser = ""
org-telegram-desktop = ""
paperwork = ""
pavucontrol = ""
personal = ""
plexamp = ""
qutepreview = ""
rapid-photo-downloader = ""
remote-viewer = ""
sandboxed-tor-browser = ""
scli = ""
shopping = ""
Signal = ""
slack = ""
snappergui = ""
songrec = ""
spotify = ""
steam = ""
streamlink-twitch-gui = ""
sun-awt-x11-xframepeer = ""
swappy = ""
taskwarrior-tui = ""
telegramdesktop = ""
".*transmission.*" = ""
udiskie = ""
vimiv = ""
virt-manager = ""
vlc = ""
vncviewer = ""
wayvnc = "󰀄"
whatsapp-desktop = ""
whatsapp-nativefier-d52542 = ""
wire = "󰁀"
wireshark-gtk = ""
wlfreerdp = "󰀄"
work = ""
xplr = ""
nemo = ""
zoom = ""

[exclude]
"" = "^$" # prevent displaying clients with empty class
